// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -I ../../ebpf/c -I ../../../ebpf/c -fsigned-char types.go

package mongo

type ConnTuple struct {
	Saddr_h  uint64
	Saddr_l  uint64
	Daddr_h  uint64
	Daddr_l  uint64
	Sport    uint16
	Dport    uint16
	Netns    uint32
	Pid      uint32
	Metadata uint32
}

type EbpfTx struct {
	Tup          ConnTuple
	Request_id   uint32
	Response_to  uint32
	Timestamp_ns uint64
	Is_error     uint8
	Pad_cgo_0    [7]byte
}
