// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -I ../../ebpf/c -I ../../../ebpf/c -fsigned-char types.go

package amqp

type ConnTuple struct {
	Saddr_h   uint64
	Saddr_l   uint64
	Daddr_h   uint64
	Daddr_l   uint64
	Sport     uint16
	Dport     uint16
	Netns     uint32
	Metadata  uint32
	Pad_cgo_0 [4]byte
}

type EbpfTx struct {
	Tup                ConnTuple
	Messages_delivered uint32
	Messages_published uint32
	Reply_code         uint8
	Identifier         [256]uint8
	Identifier_type    uint8
}

type AMQPIdentifierType int

const (
	AMQP_IDENTIFIER_TYPE_QUEUE AMQPIdentifierType = iota
	AMQP_IDENTIFIER_TYPE_EXCHANGE
	AMQP_IDENTIFIER_TYPE_ADDRESS
)
