// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -I ../../ebpf/c -I ../../../ebpf/c -fsigned-char types.go

package amqp

type ConnTuple struct {
	Saddr_h   uint64
	Saddr_l   uint64
	Daddr_h   uint64
	Daddr_l   uint64
	Sport     uint16
	Dport     uint16
	Netns     uint32
	Metadata  uint32
	Pad_cgo_0 [4]byte
}

type EbpfTx struct {
	Tup                ConnTuple
	Messages_delivered uint32
	Messages_published uint32
	Reply_code         uint8
	Exchange_or_queue  [256]uint8
	Is_exchange        uint8
}
